options:
  ssh-allow-networks:
    type: string
    default: ""
    description: "Space seperated list of subents in CIDR notation which are allowed to connect to ssh"
  ssh-allow-hosts:
    type: string
    default: ""
    description: "Space seperated list of addresses which are allowed to connect to ssh"
  enforce:
    type: boolean
    default: True
    description: Enable or disable enforcement of firewall rules. (For debugging and trouble shooting)
  use-private-addresses:
    type: boolean
    default: True
    description: By default all peers are determined by their provate-address as it is known by juju. Sometimes you may need just all addresses of the hosts.
  filter-peers-by-networks:
    type: string
    default: ""
    description: If this option is set, only peer addresses in those subnets will be used. (space seperated list of CIDR network addresses)
