options:
  ssh-allow-networks:
    type: string
    default: ""
    description: "Space seperated list of subents in CIDR notation which are allowed to connect to ssh"
  ssh-allow-hosts:
    type: string
    default: ""
    description: "Space seperated list of addresses which are allowed to connect to ssh"
